# Generated by Django 5.1.1 on 2024-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default/image.png', null=True, upload_to='images/'),
        ),
    ]
