# Generated by Django 5.1.1 on 2024-11-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_announcement'),
        ('dashboard', '0012_event_organizer_alter_event_user'),
    ]

    operations = [
    ]
