# Generated by Django 5.1.1 on 2024-12-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
