# Generated by Django 5.1.1 on 2024-12-03 06:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
