# Generated by Django 5.1.1 on 2024-12-04 11:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
