# Generated by Django 5.1.1 on 2024-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_bio',
            field=models.TextField(blank=True),
        ),
    ]
