# Generated by Django 5.1.1 on 2024-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/default_profile_image.png', null=True, upload_to='images/'),
        ),
    ]
