# Generated by Django 5.1.1 on 2024-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_profile_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='event_count',
            new_name='like_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
